# Generated by Django 5.0.6 on 2024-06-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_estudiantes_curso_camada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaDeEntrega', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profesores',
            name='profesion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
